title: Latent Hub
description: Data Science, Machine Learning Notes 

# Link settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minedeep.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Social settings
social_sites:
  github: minedeep
  linkedin: 

rss: rss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# Kramdown settings
kramdown:
  input: GFM

# Highlighter settings
highlighter: rouge

# Disqus
disqus:
  shortname: minedeep-github-io

# Google analytics
google_analytics: 

# Publish future
future: true
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#  - about.html
  #- /cv/index.md
  #- /notebook/index.md
  #- /projects/index.md

# Include this line so that travis will not explode
exclude: [vendor]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
